doc: Mention need to checkout repo
Without it, you get:

```
fatal: not in a git directory
Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌
```

See https://stackoverflow.com/questions/79605681/getting-error-fatal-not-in-a-git-repository-when-using-github-action-rossjrw